### ISSUE TITLE
Define a default nthreads parameter

### ISSUE THREAD

**Issue by nboley** [kundajelab/bds_atac#13]
I think that there should be a single n_threads option that sets the number of threads for all of the subprocesses, and then the option to specialize by setting them individually.

**Comment by leepc12** [comment]
We already have it `-nth` for all tasks. Some intensive tasks have their own `-nth_APPNAME` like `-nth_spp`.

**Comment by leepc12** [comment]
Sorry, there WAS `-nth` in previous versions. but I removed it because having multiple threads for every task is not very efficient when combined with a cluster engine like Grid Engine.

**Comment by nboley** [comment]
Can you please explain in more detail what the problem was?

**Comment by leepc12** [comment]
There are many single threaded tasks in the pipeline and softwares (like picard and bedtools) in such tasks do not support multi-threading. In Grid Engine, # of slots in a parallel environment is limited. I actually didn't want those tasks to take slots more than they need.

BDS submits a job with `qsub -pe [PE_NAME] [N_THREAD]`.

**Comment by leepc12** [comment]
Added `-nth` and the pipeline automatically allocate threads to tasks.
