### ISSUE TITLE
Error: V plot index is missing

### ISSUE THREAD

**Issue by PocketChangeJ** [kundajelab/bds_atac#23]
Hi there, 
I'm receiving an error:

00:00:00.283	Error (/bds_atac/atac.bds, line 211, pos 26): V plot index is missing ( '-tss_enrich' )!

I suppose its at the QC step - would it be possible for someone to perhaps suggest how to provide this? Thank you!

**Comment by csfoo** [comment]
Hi, 

Which genome are you using? We currently have files for hg19 and mm9 but we plan to add support for other genomes (and genome builds) soon.

The relevant files can be downloaded using the instructions listed here:
https://github.com/kundajelab/bds_atac#genome-data
You may wish to modify the parts of the script that build the bowtie index if you already have one.

Let us know if you have any further issues. 

Thanks!

**Comment by leepc12** [comment]
For mm10 and hg38, genome data for ATAQC are currently not avaiable.

I have changed that error to a warning. c1c89d0b85a91f48e6f4ad980ba1ec076ea6ec5f 
If genome data is missing for ATAQC, then the pipeline will disable ATAQC.

**Comment by PocketChangeJ** [comment]
Hi, it was mm9. 
I ended up re-loading genome files - appears it fixed the error. Thank you!
