### ISSUE TITLE
Do we need additional arguments for ATACseq?

### ISSUE THREAD

**Issue by nboley** [kundajelab/bds_atac#4]
For ATAQC, you need to define the following parameters. parameters -preseq and -vplot will be ignored since they are already included in ATAQC. See help ($ bds atac.bds) for description of all parameters.

-vplot_idx [] -ref_fa [] -blacklist [] -dnase [] -prom [] -enh [] -reg2map [] -roadmap_meta []

But Chris believes that if we set the --kundaje_lab option we don't need to. Is this correct?

**Comment by leepc12** [comment]
No, `--kundaje_lab` is no longer valid, the pipeline automatically detects Kundaje lab cluster by its hostname (take a look at `species_file` in `./conf/default.env`)

Those parameters are all needed for ATAQC including `-species [SPECIES: hg19 or mm9 or ...]`. I am updating README to add `-species` and description and how-to-get for all required files.

On Kundaje lab (or SCG3) clusters, you don't have to define any of these parameters. They are already defined in `./species/kundaje.conf` (https://github.com/kundajelab/TF_chipseq_pipeline/blob/fdcd1b821cfe4cdade0b2d035161375a3936de40/species/kundaje.conf) and these file paths will be used if you specify species with `-species [SPECIES]`.

On non-Stanford clusters, all parameters must be defined or a species file (like the above link) is needed.
