### ISSUE TITLE
re-write trim adapters

### ISSUE THREAD

**Issue by nboley** [kundajelab/bds_atac#9]
1) use functions
2) make it faster
3) buffered writes
4) remove single mismatch constraint

Here's a cleaned up version that I wrote a while ago:
https://github.com/nboley/regulatory_network_tools/blob/master/scripts/trim_ATACseq_reads.py

**Comment by csfoo** [comment]
Nathan - did you have a way of evaluating the improvement of your trimmer?
We are considering replacing this trimmer with a published equivalent (
https://github.com/jhhung/PEAT)

**Comment by nboley** [comment]
The only advantages are that it is much faster, allowed for more than 1 mismatch, and the code is cleaner. If PEAT works then I would say go with that.
